name: Check GitHub Contributions and Notify

on:
  schedule:
    - cron: "0 13 * * *" # UTC時間で毎日13時（日本時間で22時）に実行

jobs:
  check-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Contributions on Main and Master Branches
        id: check_contributions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=$(date -u +"%Y-%m-%dT00:00:00Z")
          USERNAME="${{ github.repository_owner }}"
          QUERY="{\"query\": \"query { user(login: \\\"$USERNAME\\\") { repositories(first: 100, affiliations: OWNER) { edges { node { name, ref(qualifiedName: \\\"HEAD\\\") { target { ... on Commit { history(since: \\\"$DATE\\\", until: \\\"$DATE\\\") { totalCount } } } } } } } } }\"}"

          RESPONSE=$(curl -H "Authorization: bearer $GITHUB_TOKEN" -H "Content-Type: application/json" -d "$QUERY" https://api.github.com/graphql)
          echo "Response: $RESPONSE"
          TOTAL_COUNT=$(echo $RESPONSE | jq '[.data.user.repositories.edges[].node.ref.target.history.totalCount] | add // 0')

          echo "Total contributions: $TOTAL_COUNT"
          echo "CONTRIBUTIONS_COUNT=$TOTAL_COUNT" >> $GITHUB_ENV

      - name: Send LINE Notification if No Contributions
        if: env.CONTRIBUTIONS_COUNT == '0'
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          MESSAGE: "まもなく今日が終わりますが、まだGitHubにコミットしていません！今すぐコミットしましょう！"
        run: |
          curl -X POST -H "Authorization: Bearer $LINE_TOKEN" -F "message=$MESSAGE" https://notify-api.line.me/api/notify
